// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// REQUIRES: hexagon-registered-target || target-aarch64
// RUN: %clang -Wall -Wextra -fenable-ripple -O2 -S -emit-llvm -o - %s | FileCheck %s

#include <ripple.h>
#include <stdint.h>

// CHECK-LABEL: define dso_local void @test_branch(
// CHECK-SAME: ptr noundef readonly captures(none) [[F1:%.*]], ptr noundef readonly captures(none) [[F2:%.*]], ptr noundef readonly captures(none) [[F3:%.*]], ptr noundef writeonly captures(none) [[OUT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[UNMASKEDLOAD:%.*]] = load <4 x i8>, ptr [[F2]], align 1
// CHECK-NEXT:    [[UNMASKEDLOAD39:%.*]] = load <4 x i8>, ptr [[F1]], align 1
// CHECK-NEXT:    [[UNMASKEDLOAD40:%.*]] = load <4 x i8>, ptr [[F3]], align 1
// CHECK-NEXT:    [[DOTRIPPLE_LS_INSTANCE_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <4 x i8> [[UNMASKEDLOAD39]], <4 x i8> poison, <12 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[DOTRIPPLE_LS_INSTANCE30_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <4 x i8> [[UNMASKEDLOAD40]], <4 x i8> poison, <12 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[COND12_IN_RIPPLE_LS_INSTANCE_PH_RIPPLE_PHI_VECTORIZED_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <12 x i8> [[DOTRIPPLE_LS_INSTANCE_RIPPLE_BRANCH_CLONE]], <12 x i8> [[DOTRIPPLE_LS_INSTANCE30_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE_RIPPLE_BRANCH_CLONE]], <12 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[DOTRIPPLE_LS_INSTANCE29_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <4 x i8> [[UNMASKEDLOAD]], <4 x i8> poison, <12 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND12_IN_RIPPLE_LS_INSTANCE_PH_RIPPLE_PHI_VECTORIZED38:%.*]] = shufflevector <12 x i8> [[COND12_IN_RIPPLE_LS_INSTANCE_PH_RIPPLE_PHI_VECTORIZED_RIPPLE_BRANCH_CLONE]], <12 x i8> [[DOTRIPPLE_LS_INSTANCE29_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE]], <12 x i32> <i32 0, i32 1, i32 2, i32 3, i32 16, i32 17, i32 18, i32 19, i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    store <12 x i8> [[COND12_IN_RIPPLE_LS_INSTANCE_PH_RIPPLE_PHI_VECTORIZED38]], ptr [[OUT]], align 1
// CHECK-NEXT:    ret void
//
void test_branch(uint8_t *f1, uint8_t *f2, uint8_t *f3, uint8_t *out) {
  ripple_block_t BS = ripple_set_block_shape(0, 4, 3);
  size_t id0 = ripple_id(BS, 0);
  size_t id1 = ripple_id(BS, 1);

  // This generates a branch
  uint8_t v = ripple_broadcast(BS, 0x2, f1[id0]);
  v = id1 == 1 ?  f2[id0] : v;
  v = id1 == 2 ?  f3[id0] : v;

  out[id0 + ripple_get_block_size(BS, 0) * id1] = v;
}

// CHECK-LABEL: define dso_local void @test_switch(
// CHECK-SAME: ptr noundef readonly captures(none) [[F1:%.*]], ptr noundef readonly captures(none) [[F2:%.*]], ptr noundef readonly captures(none) [[F3:%.*]], ptr noundef readonly captures(none) [[F4:%.*]], ptr noundef writeonly captures(none) [[OUT:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i8>, ptr [[F1]], align 1
// CHECK-NEXT:    [[UNMASKEDLOAD:%.*]] = load <4 x i8>, ptr [[F2]], align 1
// CHECK-NEXT:    [[UNMASKEDLOAD73:%.*]] = load <4 x i8>, ptr [[F3]], align 1
// CHECK-NEXT:    [[UNMASKEDLOAD74:%.*]] = load <4 x i8>, ptr [[F4]], align 1
// CHECK-NEXT:    [[DOTRIPPLE_LS_INSTANCE50_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE56:%.*]] = shufflevector <4 x i8> [[UNMASKEDLOAD73]], <4 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[DOTRIPPLE_LS_INSTANCE50_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE:%.*]] = shufflevector <4 x i8> [[UNMASKEDLOAD]], <4 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[DOTRIPPLE_LS_INSTANCE:%.*]] = shufflevector <4 x i8> [[TMP0]], <4 x i8> poison, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
// CHECK-NEXT:    [[COND22_IN_RIPPLE_LS_INSTANCE_PH_RIPPLE_PHI_VECTORIZED:%.*]] = select <16 x i1> <i1 false, i1 false, i1 false, i1 false, i1 true, i1 true, i1 true, i1 true, i1 poison, i1 poison, i1 poison, i1 poison, i1 poison, i1 poison, i1 poison, i1 poison>, <16 x i8> [[DOTRIPPLE_LS_INSTANCE50_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE]], <16 x i8> [[DOTRIPPLE_LS_INSTANCE]]
// CHECK-NEXT:    [[COND22_IN_RIPPLE_LS_INSTANCE_PH_RIPPLE_PHI_VECTORIZED71:%.*]] = select <16 x i1> <i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 true, i1 true, i1 true, i1 true, i1 poison, i1 poison, i1 poison, i1 poison>, <16 x i8> [[DOTRIPPLE_LS_INSTANCE50_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE56]], <16 x i8> [[COND22_IN_RIPPLE_LS_INSTANCE_PH_RIPPLE_PHI_VECTORIZED]]
// CHECK-NEXT:    [[DOTRIPPLE_LS_INSTANCE50_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE65:%.*]] = shufflevector <4 x i8> [[UNMASKEDLOAD74]], <4 x i8> poison, <16 x i32> <i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[COND22_IN_RIPPLE_LS_INSTANCE_PH_RIPPLE_PHI_VECTORIZED72:%.*]] = shufflevector <16 x i8> [[COND22_IN_RIPPLE_LS_INSTANCE_PH_RIPPLE_PHI_VECTORIZED71]], <16 x i8> [[DOTRIPPLE_LS_INSTANCE50_RIPPLE_BCAST_RIPPLE_BRANCH_CLONE65]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    store <16 x i8> [[COND22_IN_RIPPLE_LS_INSTANCE_PH_RIPPLE_PHI_VECTORIZED72]], ptr [[OUT]], align 1
// CHECK-NEXT:    ret void
//
void test_switch(uint8_t *f1, uint8_t *f2, uint8_t *f3, uint8_t *f4, uint8_t *out) {
  ripple_block_t BS = ripple_set_block_shape(0, 4, 4);
  size_t id0 = ripple_id(BS, 0);
  size_t id1 = ripple_id(BS, 1);

  // This generates a switch
  uint8_t v = ripple_broadcast(BS, 0x2, f1[id0]);
  v = id1 == 1 ?  f2[id0] : v;
  v = id1 == 2 ?  f3[id0] : v;
  v = id1 == 3 ?  f4[id0] : v;

  out[id0 + ripple_get_block_size(BS, 0) * id1] = v;
}
